server:
  port: 777

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  redis:
    database: 0
    host: 106.14.195.35
    password: azkj201918
  data:
    mongodb:
      uri: mongodb://106.14.195.35:27017/comment
  transaction:
    rollback-on-commit-failure: true
#配置pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

