server:
  port: 777

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  redis:
    database: 0
    host: 106.14.195.35
    #host: 127.0.0.1
    password: azkj201918
    #password:
  data:
    mongodb:
      uri: mongodb://106.14.195.35:27017/comment
      #uri: mongodb://127.0.0.1:27017/discuss
  transaction:
    rollback-on-commit-failure: true
#配置pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

